import {isTauri,invoke,listen,formatBytes,formatSpeed,formatTime,progressOf,statusLabel,setNotice} from './shared.js';
const $=id=>document.getElementById(id);let current=null;let live={};let unlisten=null;let selectedId=null;let requestVersion=0;let loading=false;
const DEMO={download:{id:3,fileName:'Stories-of-Shahnameh.mp4',url:'https://media.example.org/story.mp4',savePath:'~/Downloads/Stories-of-Shahnameh.mp4',totalBytes:1224065679,downloadedBytes:478517248,status:'in_progress',scheduledAt:null,bandwidthLimitKbps:null,expectedChecksum:null},resumeSupported:true,segments:[0,1,2,3].map((index)=>({index,status:index<2?'receiving':'paused',downloadedBytes:index<2?90000000:45000000,totalBytes:306016419}))};
document.addEventListener('DOMContentLoaded',async()=>{bind();if(!isTauri){current=DEMO;live={speedBytesPerSecond:5151129,etaSeconds:142};render(current);return;}const unlistenState=await listen('download://state',event=>{if(current&&event.payload.id===selectedId&&event.payload.id===current.download.id){live=event.payload;if(document.hidden)return;render(current);if(['completed','failed','cancelled'].includes(event.payload.status))load(current.download.id);}});const unlistenSelected=await listen('download://selected',event=>load(Number(event.payload)));unlisten=()=>{unlistenState();unlistenSelected();};await load();setInterval(()=>{if(!loading&&!document.hidden)load();},5000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)load();});});
function bind(){$('close').onclick=$('close-bottom').onclick=()=>invoke('hide_app_window',{label:'download-detail'});document.addEventListener('keydown',event=>{if(event.key==='Escape')invoke('hide_app_window',{label:'download-detail'});});document.querySelectorAll('[data-tab]').forEach(tab=>tab.onclick=()=>switchTab(tab.dataset.tab));$('pause-resume').onclick=control;$('cancel-download').onclick=cancel;}
function switchTab(name){document.querySelectorAll('[data-tab]').forEach(t=>{t.classList.toggle('active',t.dataset.tab===name);t.setAttribute('aria-selected',String(t.dataset.tab===name));});$('info-view').hidden=name!=='info';$('settings-view').hidden=name!=='settings';}
async function load(id=selectedId){const target=Number.isFinite(id)?id:null;if(target!==selectedId){selectedId=target;live={};}const version=++requestVersion;loading=true;try{const detail=await invoke('download_detail',{id:target});if(version!==requestVersion)return;if(detail.download.id!==selectedId)live={};selectedId=detail.download.id;current=detail;render(current);}catch(error){if(version===requestVersion)setNotice($('detail-notice'),String(error),'error');}finally{if(version===requestVersion)loading=false;}}
function render(detail){const d={...detail.download,...live};const progress=progressOf(d);$('detail-title').textContent=d.fileName;$('d-name').textContent=d.fileName;$('d-status').textContent=statusLabel(d.status);$('d-size').textContent=formatBytes(d.totalBytes||d.downloadedBytes);$('d-downloaded').textContent=formatBytes(d.downloadedBytes);$('d-speed').textContent=formatSpeed(live.speedBytesPerSecond);$('d-eta').textContent=formatTime(live.etaSeconds);$('d-resume').textContent=detail.resumeSupported?'Yes':'No';$('detail-progress').style.width=`${progress}%`;$('progress-label').textContent=`${progress.toFixed(0)}%`;$('d-url').textContent=d.url;$('d-path').textContent=d.savePath;$('d-schedule').textContent=d.scheduledAt||'Not scheduled';$('d-bandwidth').textContent=d.bandwidthLimitKbps?`${d.bandwidthLimitKbps} KB/s`:'Unlimited';$('d-checksum').textContent=d.expectedChecksum||'Not configured';const resumable=['paused','failed'].includes(d.status);$('pause-resume').textContent=resumable?'Resume':'Pause';$('pause-resume').disabled=!resumable&&!['in_progress','queued'].includes(d.status);renderSegments(detail.segments||[]);}
let lastSegments='';
function renderSegments(segments){const serialized=JSON.stringify(segments);if(serialized===lastSegments)return;lastSegments=serialized;$('segment-strip').innerHTML=segments.map(s=>`<span class="${s.status}" title="Part ${s.index+1}: ${statusLabel(s.status)}"></span>`).join('');$('segment-rows').innerHTML=segments.length?segments.map(s=>`<tr><td>${s.index+1}</td><td>${statusLabel(s.status)}</td><td>${formatBytes(s.downloadedBytes)}</td><td>${formatBytes(s.totalBytes)}</td></tr>`).join(''):'<tr><td colspan="4">No part information is available for this download.</td></tr>';}
async function control(){if(!current||loading||current.download.id!==selectedId)return;const status={...current.download,...live}.status;try{await invoke(['paused','failed'].includes(status)?'resume_download':'pause_download',{id:current.download.id});await load();}catch(error){setNotice($('detail-notice'),String(error),'error');}}
async function cancel(){if(!current||loading||current.download.id!==selectedId)return;try{await invoke('cancel_download',{id:current.download.id});await load();}catch(error){setNotice($('detail-notice'),String(error),'error');}}
window.addEventListener('unload',()=>unlisten?.());
